apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeecrs.prodready.ecr
spec:
  connectionSecretKeys:
  - kubeconfig
  defaultCompositionRef:
    name: ecr-aws
  group: prodready.ecr
  names:
    kind: CompositeECR
    plural: compositeecrs
  claimNames:
    kind: ECRClaim
    plural: ecrclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: ID of this ecr that other objects will use to refer to it.
              parameters:
                type: object
                properties:
                  region:
                    description: region for networking resources.
                    type: string

                required:
                - region